version: "3"

services:
  postgres:
    image: "bbb-demo:latest"
    env_file:
      - ".rbenv-vars"
  web:
    build: .
    image: "bbb-demo:latest"
    container_name: "bbb-demo"
    depends_on:
      - "postgres"
    env_file:
      - ".rbenv-vars"
